baseURL = "https://docs.luck6.net"
languageCode = "zh"
title = "Luck6-Docs"
theme = "book"
disablePathToLower = true
enableGitInfo = true

[languages]

[languages.zh]
  languageName = 'Chinese'
  contentDir = 'content'
  weight = 1

[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 3

[markup]
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 1
[menu]
[[menu.after]]
  name = "主站"
  url = "https://Luck6.net"
  weight = 10
[params]
  BookSection = 'basic'
  BookRepo = 'https://github.com/Luck6-Project/Luck6-Docs'
  BookEditPath = 'edit/main/content'
  BookDateFormat = 'January 2, 2006'
  BookComments = true
  BookSearch = true
